apiVersion: batch/v1
kind: Job
metadata:
  name: pi-job
spec:
  completions: 1
  backoffLimit: 3
  template:
    metadata:
      name: pi-job
    spec:
      containers:
        - name: pi
          image: perl:5.34.0
          command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
